### ISSUE TITLE
Error loading file when running mjpeg-stream.js

### ISSUE THREAD

**Issue by ryanjbaxter** [hybridgroup/node-bebop#10] opened 2015-09-29 15:57 UTC
I am trying to run the mjpeg-stream.js example but I am getting the error 

`[Error: Error loading file]`

Any idea why this is happening?  I am using node v0.12.4.

**Comment by deadprogram** [comment] 2015-09-29 16:01
Hi @ryanjbaxter pretty sure that version of node is not yet supported by this module? I cannot recall why at the moment. Can you please try an older version and see if you have same problem?

**Comment by ryanjbaxter** [comment] 2015-09-29 17:30
@deadprogram what version should i be using?

**Comment by deadprogram** [comment] 2015-09-29 17:30
I'd try 0.10.X

**Comment by ryanjbaxter** [comment] 2015-09-29 17:59
I switched to 0.10.38 and still see the same error.  I am OSX 10.10.5, not sure if that makes a difference.

**Comment by ryanjbaxter** [comment] 2015-10-02 13:48
Anyone have any other suggestions as to why this is not working?

**Comment by deadprogram** [comment] 2015-10-02 17:34
Do you have `ffmpeg` installed on your machine? I just realized the docs are missing the info that this is a needed prereq. The installation info for this on OSX  if you are using Homebrew is:

```
brew install ffmpeg
```

**Comment by ryanjbaxter** [comment] 2015-10-02 18:34
yes I have ffmpeg installed

**Comment by nelson-liu** [comment] 2016-02-14 06:30
ping @ryanjbaxter @deadprogram did you ever find a solution to this error?

**Comment by ryanjbaxter** [comment] 2016-02-14 19:49
@nelson-liu no I did not

**Comment by deadprogram** [comment] 2016-04-15 14:48
Hi, @ryanjbaxter can you please retry this code with the new 0.5.0 node-bebop release? I am not able to reproduce myself with this version. I will leave this issue open to await some additional info.

**Comment by deadprogram** [comment] 2016-12-27 10:03
Closing due to age of issue. Please reopen if needed.

**Closed by deadprogram** 2016-12-27 10:03 UTC
